### ISSUE TITLE
CrearJugador

### ISSUE THREAD

**Issue by RomanMillan** [RomanMillan/juegoJaca#3]
En la clase Juego en el metodo privado crearJugador(PlayerType tipo) 
entiendo que hay que crear un objeto jugador, unas coordenadas e insertarlas en el arrayList de coordenadaJugadores y en HashMap de tablero, para que aparezca junto con los demás objetos, pero hay un problema y es que no me deja ya que el HashMap solo acepta
Coordenada y Element < y yo intento insertar el Jugador.
Necesito ayuda ya que no se que hay que hacer.

**Comment by ioliasa** [comment]
Estas seguro que te da problemas?? Jugador extiende de Element por lo que ko deberías tener ningún problema

**Comment by RomanMillan** [comment]
paso la captura
![s](https://user-images.githubusercontent.com/74763033/168273016-6e7a933f-23d9-442e-86f2-6202ec2f6882.PNG)

**Comment by ioliasa** [comment]
Te he dado la pista en lo anterior, mira si has definido bien Jugador

**Comment by RomanMillan** [comment]
Inma pero si pongo que la clase Jugador extiende de Element me obliga a cambiar el constructor a 
	public Jugador(ElementType type) {
		super(type);
	}
y en la documentación pone que en vez de ElementType es PlayerType para que pueda asignarlo a la variable PlayerType player.

**Comment by ioliasa** [comment]
Lo primero es lo primero, mira lo que dice sobre jugador
![image](https://user-images.githubusercontent.com/47950846/168464448-42ee1439-d2bc-41f6-b67e-842db0c59e73.png)

Así, que si o si tiene que extender de Element.

Luego en el constructor, efectivamente lo que le pasa es un PlayerType porque necesita saber de qué tipo es, pero tu del playerType puedes sacar el ElementType con el atributo name. Lo vimos en clase

**Comment by RomanMillan** [comment]
resuelto
