### ISSUE TITLE
Peta al mover jugador

### ISSUE THREAD

**Issue by RomanMillan** [RomanMillan/juegoJaca#4]
Inma tengo un error cuando ejecuto el juego. 
El juego se genera todo bien, pero a la hora de mover al jugador se peta y según pone en el error es en el método getNextPosition(),
ni idea que tengo mal.
También una de las veces que he ejecutado el juego para probar si ya funcionaba, me a puesto que el jugador empezaba con 0 movimientos, algo que creo que también está mal.

**Comment by ioliasa** [comment]
En cuanto a lo de que el jugador tiene 0 movimientos tienes que repasar el método  getVelocidadParaLuchar de la clase Jugador, mira si el número que te genera puede ser de 1 a la velocidad máxima o no.

En cuanto a lo que peta, ¿se te ha ocurrido ver dónde peta?. Porque a mi me ha dicho que lo que falla es esta línea. Repásala
if(direction != 'N' || direction != 'S'|| direction != 'E'|| direction != 'O') {
			throw new JuegoException("Direccion incorrecta");
		}
