### ISSUE TITLE
Error al mover jugadores

### ISSUE THREAD

**Issue by RomanMillan** [RomanMillan/juegoJaca#5]
Cuando un jugador le toca mover y  mueve el primer movimiento funciona bien, pero al siguiente cambia de jugador aunque al primer jugador le toque 4 movimientos por ejemplo. 
Ej cuando empieza le toca al elfo con 4 movimientos , el primero lo hace correcto, pero al siguiente cambia al guerrero y así.
He mirado los metodos de getNextPosicion(),  cambiaJugadorAPosicion, getMovimientoJugador() pero no he detectado ningún error.

**Comment by ioliasa** [comment]
Usa el debuger y mira el método cambiaJugadorAPosicion. Comprueba que los atributos se quedan bien

**Comment by RomanMillan** [comment]
arreglado
